services:
  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data

  patient-service:
    build:
      context: .
      dockerfile: ./patient-service/Dockerfile
    ports:
      - "50051:50051"
    restart: unless-stopped
    environment:
      GRPC_PORT: 50051
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka

  appointment-service:
    build:
      context: .
      dockerfile: ./appointment-service/Dockerfile
    ports:
      - "50052:50052"
    restart: unless-stopped
    environment:
      GRPC_PORT: 50052
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka

  prescription-service:
    build:
      context: .
      dockerfile: ./prescription-service/Dockerfile
    ports:
      - "50053:50053"
    restart: unless-stopped
    environment:
      GRPC_PORT: 50053
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      PORT: 3000
      PATIENT_SERVICE_ADDR: patient-service:50051
      APPOINTMENT_SERVICE_ADDR: appointment-service:50052
      PRESCRIPTION_SERVICE_ADDR: prescription-service:50053
    depends_on:
      - patient-service
      - appointment-service
      - prescription-service

volumes:
  kafka_data:
